version: "3.9"

services:
  my_postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dians_baza
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init_utf8.sql:/docker-entrypoint-initdb.d/init.sql:ro

  python_app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dians_baza
      POSTGRES_HOST: my_postgres
      POSTGRES_PORT: 5432
    depends_on:
      - my_postgres

  java_app:
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: java_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_postgres:5432/dians_baza
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - my_postgres

  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - python_app

volumes:
  pgdata:
